name: MineQuest-HeroChat
main: com.theminequest.MineQuest.MineQuest-HeroChat
version: ${build.version}

author: Echobob
authors: [Xu_R, phrstbrn, Ltan, Makraiz, Blaksmith]

description: This plugin, and its add-ons expands Minecraft to add in Npcs, Quests, and custom events to create a Role-Play enviorment in Minecraft
website: www.theminequest.com

load: POSTWORLD

depend: [MineQuest]
softdepend: [Vault]